export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_RESPONSE = 'SIGN_UP_RESPONSE';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_RESPONSE = 'SIGN_IN_RESPONSE';
export const LOG_OUT = 'LOG_OUT';