export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_RESPONSE = 'SIGN_UP_RESPONSE';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_RESPONSE = 'SIGN_IN_RESPONSE';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_RESPONSE = 'CREATE_POST_RESPONSE';
export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_RESPONSE = 'FETCH_POST_RESPONSE';